/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Components;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import config.DesignConstants;

public class PageHeader extends javax.swing.JPanel {

        private GridBagConstraints gridBagConstraints;
    private DynamicForm form;

    public PageHeader(String entity, Object[][] formStructure) {
        initComponents();

        form = new DynamicForm(formStructure, entity);

        addBtn.setText("Add a " + entity);
        entityName.setText("Manage your " + entity + "s ");

        setLayout(new GridBagLayout());
        /*gridBagConstraints = new GridBagConstraints();

        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        gridBagConstraints.insets = new Insets(10, 20, 10, 10);
        add(jLayeredPane1, gridBagConstraints);*/

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.anchor = GridBagConstraints.CENTER;
        gridBagConstraints.insets = new Insets(10, 0, 10, 10);
        add(entityName, gridBagConstraints);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = GridBagConstraints.EAST;
        gridBagConstraints.insets = new Insets(10, 10, 10, 40);
        add(addBtn, gridBagConstraints);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addBtn = new javax.swing.JButton();
        entityName = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(DesignConstants.WHITE_COLOR);
        setMaximumSize(new java.awt.Dimension(950, 79));
        setMinimumSize(new java.awt.Dimension(1300, 60));
        setPreferredSize(new java.awt.Dimension(1300, 60));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addBtn.setForeground(DesignConstants.WHITE_COLOR);
        addBtn.setText("Add a Doctor");
        addBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1162, 18, -1, -1));
        addBtn.setBackground(DesignConstants.SECONDARY_COLOR);

        entityName.setFont(DesignConstants.HEADING_FONT3);
        entityName.setForeground(DesignConstants.PRIMARY_COLOR);
        add(entityName, new org.netbeans.lib.awtextra.AbsoluteConstraints(927, 18, -1, -1));

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
//         DynamicForm form = new DynamicForm(formStructure);
         form.setVisible(true);
    }//GEN-LAST:event_addBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Dashboard.DashboardPage back = new Dashboard.DashboardPage();
        back.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel entityName;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
