package Auth;

import Dashboard.DashboardPage;
import DbConfig.CrudManager;
import common.commonMethods;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.*;
import config.DesignConstants;

public class LoginPage extends javax.swing.JFrame {
    
    public LoginPage() {
        // Initialize components

        // Custom initialization
        initComponents();
        
        commonMethods cm = new commonMethods();
        cm.resizer("src/Images/a.png", image);
        cm.resizer("src/Images/logo.png", logo);

        // Add component listener to handle resizing
        image.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                cm.resizer("src/Images/a.png", image);
            }
        });
        
        logo.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                cm.resizer("src/Images/logo.png", logo);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        image = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        logo = new javax.swing.JLabel();
        welcome = new javax.swing.JLabel();
        emailVal = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        passLabel = new javax.swing.JLabel();
        passVal = new javax.swing.JPasswordField();
        loginText = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel3 = new javax.swing.JLabel();
        RegisterRedirect = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login_Page");
        setBackground(new java.awt.Color(252, 252, 252));
        setMinimumSize(DesignConstants.FRAME_SIZE);

        jPanel1.setMaximumSize(DesignConstants.FRAME_SIZE);
        jPanel1.setMinimumSize(DesignConstants.FRAME_SIZE);
        jPanel1.setPreferredSize(DesignConstants.FRAME_SIZE);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        image.setForeground(new java.awt.Color(255, 255, 255));
        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/a.png"))); // NOI18N
        image.setMaximumSize(DesignConstants.HALF_FRAME_SIZE);
        image.setMinimumSize(DesignConstants.HALF_FRAME_SIZE);
        image.setPreferredSize(DesignConstants.HALF_FRAME_SIZE);
        jPanel1.add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 653, 740));

        jLayeredPane2.setPreferredSize(new java.awt.Dimension(412, 742));
        jLayeredPane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        logo.setText("logo");
        logo.setMaximumSize(DesignConstants.HALF_FRAME_SIZE);
        logo.setMinimumSize(DesignConstants.HALF_FRAME_SIZE);
        logo.setPreferredSize(DesignConstants.HALF_FRAME_SIZE);
        jLayeredPane2.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 86, 157, 161));

        welcome.setBackground(new java.awt.Color(117, 184, 228));
        welcome.setFont(DesignConstants.HEADING_FONT1);
        welcome.setForeground(new java.awt.Color(76, 126, 247));
        welcome.setLabelFor(welcome);
        welcome.setText("Healthcare Management");
        welcome.setMaximumSize(new java.awt.Dimension(300, 25));
        welcome.setMinimumSize(new java.awt.Dimension(300, 25));
        welcome.setPreferredSize(new java.awt.Dimension(118, 25));
        jLayeredPane2.add(welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 44, 323, 36));

        emailVal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailValActionPerformed(evt);
            }
        });
        jLayeredPane2.add(emailVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 302, 168, 31));

        emailLabel.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(93, 96, 97));
        emailLabel.setText("Email");
        jLayeredPane2.add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 307, 49, 19));

        passLabel.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        passLabel.setForeground(new java.awt.Color(86, 79, 79));
        passLabel.setText("Password");
        jLayeredPane2.add(passLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 357, -1, -1));

        passVal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passValActionPerformed(evt);
            }
        });
        jLayeredPane2.add(passVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 353, 168, 31));

        loginText.setBackground(new java.awt.Color(117, 184, 228));
        loginText.setFont(DesignConstants.HEADING_FONT2);
        loginText.setForeground(new java.awt.Color(76, 126, 247));
        loginText.setLabelFor(welcome);
        loginText.setText("Login to your account");
        loginText.setPreferredSize(new java.awt.Dimension(118, 25));
        jLayeredPane2.add(loginText, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 253, 192, -1));

        jLabel3.setForeground(new java.awt.Color(16, 15, 15));
        jLabel3.setText("Don't have an account? Click on");

        RegisterRedirect.setFont(DesignConstants.GLOBAL_FONT);
        RegisterRedirect.setForeground(new java.awt.Color(16, 118, 207));
        RegisterRedirect.setText("Register");
        RegisterRedirect.setBorder(DesignConstants.BOTTOM_BORDER);
        RegisterRedirect.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegisterRedirect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisterRedirectMouseClicked(evt);
            }
        });

        loginBtn.setBackground(DesignConstants.PRIMARY_COLOR);
        loginBtn.setText("Login Now");
        loginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(RegisterRedirect, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(loginBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RegisterRedirect))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(loginBtn)
                        .addGap(75, 75, 75)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegisterRedirect))
                .addGap(26, 26, 26)
                .addComponent(loginBtn)
                .addContainerGap())
        );

        jLayeredPane2.add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 396, -1, -1));

        jPanel1.add(jLayeredPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 90, -1, 533));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1145, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void emailValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailValActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailValActionPerformed

    private void passValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passValActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passValActionPerformed

    private void RegisterRedirectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterRedirectMouseClicked
        RegisterPage registerPage = new RegisterPage();
        this.setVisible(false);
        registerPage.setVisible(true);
    }//GEN-LAST:event_RegisterRedirectMouseClicked

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        
        String email = emailVal.getText();
        String pass = passVal.getText();
        
        if (email == null || email.isEmpty()
                || pass == null || pass.isEmpty()) {
            
            commonMethods.showDialogPane("error", "All fields are required");
            return;
        }
        
        boolean success = CrudManager.login(email, pass);
        
        if (success) {
//            commonMethods.showDialogPane("success", "Successfully! Login the user");
            DashboardPage dashboardPage = new DashboardPage();
            this.setVisible(false);
            dashboardPage.setVisible(success);
            System.out.println(success);
        } else {
            commonMethods.showDialogPane("error", "Invalid email or password");
        }
        
    }//GEN-LAST:event_loginBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {

        // Create and display the login page
        SwingUtilities.invokeLater(() -> {
            new LoginPage().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RegisterRedirect;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailVal;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel loginText;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel passLabel;
    private javax.swing.JPasswordField passVal;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
