package Auth;

import DbConfig.CrudManager;
import common.commonMethods;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.*;
import config.DesignConstants;

public class RegisterPage extends javax.swing.JFrame {

    public RegisterPage() {
    
        initComponents();
        
        commonMethods cm = new commonMethods();
        cm.resizer("src/Images/a.png", image);
        cm.resizer("src/Images/logo.png", logo);

        // Add component listener to handle resizing
        image.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                cm.resizer("src/Images/a.png", image);
            }
        });

        logo.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                cm.resizer("src/Images/logo.png", logo);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        image = new javax.swing.JLabel();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        welcome = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        nameVal = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        passLabel = new javax.swing.JLabel();
        passVal = new javax.swing.JPasswordField();
        loginText = new javax.swing.JLabel();
        confirmPassVal = new javax.swing.JPasswordField();
        passLabel1 = new javax.swing.JLabel();
        emailLabel1 = new javax.swing.JLabel();
        emailVal = new javax.swing.JTextField();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel3 = new javax.swing.JLabel();
        registerBtn = new javax.swing.JButton();
        loginRedirect = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login_Page");
        setBackground(new java.awt.Color(252, 252, 252));
        setMinimumSize(DesignConstants.FRAME_SIZE);

        jPanel1.setMaximumSize(DesignConstants.FRAME_SIZE);
        jPanel1.setMinimumSize(DesignConstants.FRAME_SIZE);
        jPanel1.setPreferredSize(DesignConstants.FRAME_SIZE);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        image.setForeground(new java.awt.Color(255, 255, 255));
        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/a.png"))); // NOI18N
        image.setMaximumSize(DesignConstants.HALF_FRAME_SIZE);
        image.setMinimumSize(DesignConstants.HALF_FRAME_SIZE);
        image.setPreferredSize(DesignConstants.HALF_FRAME_SIZE);
        jPanel1.add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 648, 668));

        jLayeredPane3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcome.setBackground(new java.awt.Color(117, 184, 228));
        welcome.setFont(DesignConstants.HEADING_FONT1);
        welcome.setForeground(new java.awt.Color(76, 126, 247));
        welcome.setLabelFor(welcome);
        welcome.setText("Healthcare Management");
        welcome.setMaximumSize(new java.awt.Dimension(256, 25));
        welcome.setMinimumSize(new java.awt.Dimension(256, 25));
        welcome.setPreferredSize(new java.awt.Dimension(118, 25));
        jLayeredPane3.add(welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 6, 291, 36));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        jLayeredPane3.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 48, 154, 153));

        nameVal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameValActionPerformed(evt);
            }
        });
        jLayeredPane3.add(nameVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 238, 168, 31));

        nameLabel.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(93, 96, 97));
        nameLabel.setText("Name");
        jLayeredPane3.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 250, 49, 19));

        passLabel.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        passLabel.setForeground(new java.awt.Color(86, 79, 79));
        passLabel.setText("Password");
        jLayeredPane3.add(passLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 349, -1, -1));

        passVal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passValActionPerformed(evt);
            }
        });
        jLayeredPane3.add(passVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 345, 168, 31));

        loginText.setBackground(new java.awt.Color(117, 184, 228));
        loginText.setFont(DesignConstants.HEADING_FONT2);
        loginText.setForeground(new java.awt.Color(76, 126, 247));
        loginText.setLabelFor(welcome);
        loginText.setText("Create your new account");
        loginText.setPreferredSize(new java.awt.Dimension(118, 25));
        jLayeredPane3.add(loginText, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 207, 333, -1));

        confirmPassVal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmPassValActionPerformed(evt);
            }
        });
        jLayeredPane3.add(confirmPassVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 398, 168, 31));

        passLabel1.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        passLabel1.setForeground(new java.awt.Color(86, 79, 79));
        passLabel1.setText("Confirm Password");
        jLayeredPane3.add(passLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 402, -1, -1));

        emailLabel1.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        emailLabel1.setForeground(new java.awt.Color(93, 96, 97));
        emailLabel1.setText("Email");
        jLayeredPane3.add(emailLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 301, 49, 19));

        emailVal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailValActionPerformed(evt);
            }
        });
        jLayeredPane3.add(emailVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 296, 168, 31));

        jLayeredPane2.setAlignmentX(2.5F);
        jLayeredPane2.setAlignmentY(4.5F);

        jLabel5.setForeground(new java.awt.Color(16, 15, 15));
        jLabel5.setText("Don't have an account? Click on");

        jLabel6.setFont(DesignConstants.GLOBAL_FONT);
        jLabel6.setForeground(new java.awt.Color(16, 118, 207));
        jLabel6.setText("Register");
        jLabel6.setBorder(DesignConstants.BOTTOM_BORDER);
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLayeredPane2.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap())
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(8, Short.MAX_VALUE))
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLayeredPane3.add(jLayeredPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 694, -1, -1));

        jLabel3.setForeground(new java.awt.Color(16, 15, 15));
        jLabel3.setText("Already have an account? Click on");

        registerBtn.setBackground(DesignConstants.PRIMARY_COLOR);
        registerBtn.setText("Register Now");
        registerBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });

        loginRedirect.setFont(DesignConstants.GLOBAL_FONT);
        loginRedirect.setForeground(new java.awt.Color(16, 118, 207));
        loginRedirect.setText("Login");
        loginRedirect.setBorder(DesignConstants.BOTTOM_BORDER);
        loginRedirect.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginRedirect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginRedirectMouseClicked(evt);
            }
        });

        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(registerBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(loginRedirect, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loginRedirect))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(registerBtn)
                        .addGap(62, 62, 62)))
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loginRedirect))
                .addGap(18, 18, 18)
                .addComponent(registerBtn)
                .addContainerGap())
        );

        jLayeredPane3.add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 447, -1, -1));

        jPanel1.add(jLayeredPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 50, -1, 722));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1120, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nameValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameValActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameValActionPerformed

    private void passValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passValActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passValActionPerformed

    private void confirmPassValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPassValActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmPassValActionPerformed

    private void emailValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailValActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailValActionPerformed

    private void loginRedirectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginRedirectMouseClicked
        LoginPage loginPage = new LoginPage();
        this.setVisible(false);
        loginPage.setVisible(true);
    }//GEN-LAST:event_loginRedirectMouseClicked

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        String name = nameVal.getText();
        String email = emailVal.getText();
        String pass = passVal.getText();
        String confirmPass = confirmPassVal.getText();

        if (name == null || name.isEmpty()
                || email == null || email.isEmpty()
                || pass == null || pass.isEmpty()
                || confirmPass == null || confirmPass.isEmpty()) {

            commonMethods.showDialogPane("error", "All fields are required");
            return;
        }

        if (!pass.equals(confirmPass)) {
            commonMethods.showDialogPane("error", "Password and confirm password did not match");
            return;
        }
        boolean success = CrudManager.create("users", "name,email,password", new Object[]{name, email, pass});

        if (success) {
            commonMethods.showDialogPane("success", "Successfully! created the user");
        } else {
            commonMethods.showDialogPane("error", "Error while createing the user");
        }
    }//GEN-LAST:event_registerBtnActionPerformed

    /**
     * @param args the command line arguments
     */
public static void main(String[] args) {

        // Create and display the register page
        SwingUtilities.invokeLater(() -> {
            new RegisterPage().setVisible(true);
        });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirmPassVal;
    private javax.swing.JLabel emailLabel1;
    private javax.swing.JTextField emailVal;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel loginRedirect;
    private javax.swing.JLabel loginText;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameVal;
    private javax.swing.JLabel passLabel;
    private javax.swing.JLabel passLabel1;
    private javax.swing.JPasswordField passVal;
    private javax.swing.JButton registerBtn;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
